@startuml
start
:@Request.application._call_(http_request);
:WPSRequest(http_request);
:WPSRequest.operation;
if (is Getcapabilities) then (true)
 :get_capabilities();
else (false)
  if (is DescribeProcess) then (true)
   :describe();
  else (false)
    if (is Execute) then (true)
     :execute();
    else (false)
       :raise RuntimeError('Unknown operation');
    endif
  endif
endif
:update_response();
stop
@enduml