@startuml

class Object

'class Job{
'process
'method
'wps_request
'wps_response
'dump()
'load()
'run()
'}

interface Processing{
job
__init__()
start()
cancel()
}

class Scheduler{
start()
run_job()
}


class MultiProcessing{
start()
}

class Container{
port
client
cntnr
__init__()
_create()
_assign_port()
_execute()
_parse_outputs()
start()
stop()
cancel()
pause()
unpause()
}

Object<|-- Processing
Processing<|-- MultiProcessing
Processing<|-- Container
Processing<|-- Scheduler
@enduml