@startuml
start
:process = Process();
:mode= get_config_value('mode');
if (is Scheduler) then (true)
 -Scheduler();
else (false)
 if (is Docker) then (true)
 -Container();
 else (false)
  -MultiProcessing();
 endif
endif
:process.start();
stop
@enduml