@startuml
(*) --> execute()
--> "_execute_process()"
if ""
note left
if async
end note
 -->[true] if ""
 note left
 if running < maxparallel
 end note
  -->[true] _run_async()
  -->pywps.processing.Process()
  -->Process.start()
  -->===BEFORE_RETURN===
 else
  -->[false] _store_process()
  -->===BEFORE_RETURN===
 endif
else
 -->[false] if ""
 note right
 if running < maxparallel
 end note
  -->[true] _run_process()
  -->===BEFORE_RETURN===
 else
  -->[false] raise ServerBusy
  -->===BEFORE_RETURN===
 endif
endif
===BEFORE_RETURN===-->return WPSResponse
-->(*)
@enduml